name: Deploy Obrigenie Web

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check .NET version
        run: dotnet --version

      - name: Publish Blazor WASM
        run: dotnet publish ./Obrigenie.csproj -c Release -o ./publish

      - name: Deploy static files
        run: |
          sudo mkdir -p /var/www/obrigenie-web
          sudo rm -rf /var/www/obrigenie-web/*
          sudo cp -r ./publish/wwwroot/* /var/www/obrigenie-web/
          sudo chown -R www-data:www-data /var/www/obrigenie-web
          sudo systemctl restart nginx
          echo "Obrigenie Web deployed successfully!"
# upda